FROM rust:1.82.0-slim AS build
WORKDIR /usr/src/backend
COPY . .
RUN cargo install --release --path .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/backend /usr/local/bin/backend
CMD ["backend"]
