FROM rust:1.82.0-slim AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock src ./
RUN cargo build --release

FROM scratch
COPY --from=builder /app/target/release/backend /backend
EXPOSE 8080
CMD ["/backend"]
