"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Callable
from ..core.message_router import MessageRouter

"""
MQTT client for communication with the MQTT broker.
"""
logger = ...
@dataclass
class MQTTMessage:
    """MQTT message container."""
    topic: str
    payload: dict[str, Any]
    qos: int = ...
    retain: bool = ...


class MQTTClient:
    """
    MQTT client for publishing and subscribing to MQTT topics.
    Handles reconnection and message routing.
    """
    def __init__(self, message_router: MessageRouter) -> None:
        ...
    
    async def connect(self): # -> None:
        """Connect to the MQTT broker."""
        ...
    
    def subscribe(self, topic: str, callback: Callable[[dict[str, Any]], None]): # -> None:
        """Subscribe to an MQTT topic."""
        ...
    
    def publish(self, message: MQTTMessage): # -> bool:
        """Publish a message to an MQTT topic."""
        ...
    
    async def disconnect(self): # -> None:
        """Disconnect from the MQTT broker."""
        ...
    


