"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Callable, TypeVar

"""
Message routing system for handling internal communication.
"""
T = TypeVar('T')
class MessageType(StrEnum):
    """Enum representing different types of messages in the system."""
    SENSOR_READING = ...
    DEVICE_CONTROL = ...
    SYSTEM_EVENT = ...
    PROFILE_UPDATE = ...
    DEVICE_DATA = ...
    DEVICE_MEASUREMENT = ...
    DEVICE_ERROR = ...


@dataclass
class Message:
    """Base message class for internal communication."""
    msg_type: MessageType
    payload: dict[str, Any]
    source: str = ...
    timestamp: float | None = ...


class MessageRouter:
    """
    Handles routing of internal messages between components.
    """
    def __init__(self) -> None:
        ...
    
    def subscribe(self, msg_type: MessageType, callback: Callable[[Message], None]): # -> None:
        """Register a callback for a specific message type."""
        ...
    
    def publish(self, message: Message): # -> None:
        """Publish a message to all subscribed handlers."""
        ...
    
    def broadcast_device_data(self, device_data: dict[str, Any]) -> None:
        """Broadcast a full device data message.
        
        Args:
            device_data: Dictionary containing complete device data
            
        Raises:
            ValueError: If device_id is missing from device_data
        """
        ...
    
    def broadcast_measurement(self, device_id: str, measurement_type: str, value: float, unit: str | None = ..., timestamp: float | None = ...) -> None:
        """Broadcast a single measurement update.
        
        Args:
            device_id: ID of the device
            measurement_type: Type of measurement (e.g., 'temperature', 'humidity')
            value: Numeric value of the measurement
            unit: Unit of measurement (e.g., '°C', '%')
            timestamp: Optional timestamp in seconds since epoch
        """
        ...
    
    def broadcast_error(self, device_id: str, error_code: str, message: Message, timestamp: str | None = ...) -> None:
        """Broadcast a device error.
        
        Args:
            device_id: Unique identifier for the device
            error_code: Error code identifier
            message: Human-readable error message
            timestamp: Optional timestamp in ISO format (defaults to current time)
        """
        ...
    
    def broadcast_device_status(self, device_id: str, status: str, location: str | None = ...) -> None:
        """Broadcast a device status update.
        
        Args:
            device_id: Unique identifier for the device
            status: New status (e.g., 'online', 'offline', 'maintenance')
            location: Optional location update
        """
        ...
    
    def broadcast_system_event(self, event_type: str, message: str, data: dict[str, Any] | None = ...) -> None:
        """Broadcast a system event.
        
        Args:
            event_type: Type of system event
            message: Human-readable message
            data: Additional event data
        """
        ...
    
    def send_device_control(self, device_type: str, device_id: str, command: str, params: dict[str, Any] | None = ...): # -> None:
        """Helper method to send device control commands."""
        ...
    


